oe_newsroom.settings:
  type: config_object
  label: 'Newsroom settings'
  mapping:
    hash_method:
      type: string
      label: 'Used hashing method'
    normalized:
      type: boolean
      label: 'E-mail address should be normalized?'
    universe:
      type: string
      label: 'Universe ID from Newsroom'
    app:
      type: string
      label: 'App ID from Newsroom'

oe_newsroom.messenger:
  type: config_object
  label: 'Messenger config'
  mapping:
    class:
      type: string
      label: 'Messenger class'
