<?php

/**
 * @file
 * Hook implementations for the OpenEuropa Newsroom Newsletter module.
 */

declare(strict_types=1);

/**
 * Implements hook_local_tasks_alter().
 */
function oe_newsroom_newsletter_local_tasks_alter(&$local_tasks) {
  // Redirect original configuration translation tab to second level, with this
  // it will make more sense on the UI and fixing the tab display issue too.
  if (!empty($local_tasks['config_translation.local_tasks:config_translation.item.overview.oe_newsroom_newsletter.settings'])) {
    $local_tasks['config_translation.local_tasks:config_translation.item.overview.oe_newsroom_newsletter.settings']['parent_id'] = 'oe_newsroom_newsletter.settings.primary';
  }
}

/**
 * Implements hook_locale_translation_projects_alter().
 */
function oe_newsroom_newsletter_locale_translation_projects_alter(&$projects) {
  $projects['oe_newsroom_newsletter']['info']['interface translation server pattern'] = \Drupal::service('extension.list.module')->getPath('oe_newsroom_newsletter') . '/translations/%project-%language.po';
}

/**
 * Implements hook_preprocess_block().
 */
function oe_newsroom_newsletter_preprocess_block(array &$variables) {
  if ($variables['plugin_id'] === 'oe_newsroom_newsletter_subscription_block') {
    $variables['title_attributes']['class'][] = 'block-title-' . $variables['elements']['content']['#id'];
  }
}
