<?php

/**
 * @file
 * Hook implementations for the OpenEuropa Newsroom Newsletter module.
 */

declare(strict_types = 1);

/**
 * Implements hook_local_tasks_alter().
 */
function oe_newsroom_newsletter_local_tasks_alter(&$local_tasks) {
  // Redirect original configuration translation tab to second level, with this
  // it will make more sense on the UI and fixing the tab display issue too.
  if (!empty($local_tasks['config_translation.local_tasks:config_translation.item.overview.oe_newsroom_newsletter.settings'])) {
    $local_tasks['config_translation.local_tasks:config_translation.item.overview.oe_newsroom_newsletter.settings']['parent_id'] = 'oe_newsroom_newsletter.settings_tab.collection';
  }
}
